version: '3.7'

services:
  db:
    build: ./database/.
    container_name: postgres
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_pwd
      - POSTGRES_DB=my_db
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    build: "./keycloak/."
    command: 
      [ "start-dev", "--http-port 8887" ]
    depends_on:
      - db
    ports:
      - "8887:8887"
    volumes:
      - ./keycloak/data:/opt/keycloak/data/
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_DB_USERNAME=my_user
      - KC_DB_PASSWORD=my_pwd
      - KC_HOSTNAME=192.168.0.2
      - KC_HOSTNAME_PORT=8887
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_SPI_LOGIN_PROTOCOL_OPENID_CONNECT_LEGACY_LOGOUT_REDIRECT_URI=true

  app:
    build: "../medicine-api/."
    command: "npm run dev"
    working_dir: /home/node/app
    environment:
      - TZ=America/Sao_Paulo
    env_file:
      - environment.env
    expose:
      - "8080"
    ports:
      - "8080:8080"